_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    DEPTH: 34x
    FEAT_DIM: 512
    WITH_IBN: True

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: logs/dukemtmc/bagtricks_R34-ibn
